import { LeaderboardUser, StatsData } from './types';

export const leaderboardData: LeaderboardUser[] = [
  {
    rank: 1,
    name: 'Ahmad Rizki',
    xp: 2850,
    level: 5,
    avatar: 'AR',
    streak: 15,
    lessonsCompleted: 25,
    isCurrentUser: false,
  },
  {
    rank: 2,
    name: 'Siti Nurhaliza',
    xp: 2640,
    level: 5,
    avatar: 'SN',
    streak: 12,
    lessonsCompleted: 23,
    isCurrentUser: false,
  },
  {
    rank: 3,
    name: 'Budi Santoso',
    xp: 2420,
    level: 4,
    avatar: 'BS',
    streak: 8,
    lessonsCompleted: 21,
    isCurrentUser: false,
  },
  {
    rank: 4,
    name: 'Maya Sari',
    xp: 2180,
    level: 4,
    avatar: 'MS',
    streak: 10,
    lessonsCompleted: 19,
    isCurrentUser: false,
  },
  {
    rank: 5,
    name: 'Doni Pratama',
    xp: 1950,
    level: 4,
    avatar: 'DP',
    streak: 6,
    lessonsCompleted: 18,
    isCurrentUser: false,
  },
  {
    rank: 6,
    name: 'Rina Wati',
    xp: 1720,
    level: 3,
    avatar: 'RW',
    streak: 9,
    lessonsCompleted: 16,
    isCurrentUser: false,
  },
  {
    rank: 7,
    name: 'Pengguna ISYARA',
    xp: 1250,
    level: 3,
    avatar: 'PI',
    streak: 0,
    lessonsCompleted: 12,
    isCurrentUser: true,
  },
  {
    rank: 8,
    name: 'Andi Wijaya',
    xp: 1180,
    level: 3,
    avatar: 'AW',
    streak: 4,
    lessonsCompleted: 11,
    isCurrentUser: false,
  },
  {
    rank: 9,
    name: 'Lisa Permata',
    xp: 980,
    level: 2,
    avatar: 'LP',
    streak: 3,
    lessonsCompleted: 9,
    isCurrentUser: false,
  },
  {
    rank: 10,
    name: 'Rudi Hartono',
    xp: 850,
    level: 2,
    avatar: 'RH',
    streak: 2,
    lessonsCompleted: 8,
    isCurrentUser: false,
  },
];

export const statsData: StatsData = {
  totalUsers: 156,
  highestXp: 2850,
  averageXp: 1420,
};

