import type { CategoryData } from './types';

export const categories: Record<string, CategoryData> = {
  letters: {
    name: 'Huruf',
    items: [
      'A',
      'B',
      'C',
      'D',
      'E',
      'F',
      'G',
      'H',
      'I',
      'J',
      'K',
      'L',
      'M',
      'N',
      'O',
      'P',
      'Q',
      'R',
      'S',
      'T',
      'U',
      'V',
      'W',
      'X',
      'Y',
      'Z',
    ],
    description: 'Kuis alfabet BISINDO A-Z',
  },
  numbers: {
    name: 'Angka',
    items: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
    description: 'Kuis angka BISINDO 0-9',
  },
  words: {
    name: 'Kata',
    items: [
      'HALO',
      'TERIMA KASIH',
      'MAAF',
      'TOLONG',
      'SELAMAT',
      'NAMA',
      'SAYA',
      'KAMU',
    ],
    description: 'Kuis kata-kata dasar BISINDO',
  },
};
